# Generated by Django 2.0.2 on 2018-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_1_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstQuestion', models.CharField(max_length=120, verbose_name='A triangle has 2 angles each equal to 60 degrees. What type of triangle is it?')),
                ('secondQuestion', models.FloatField(verbose_name='The triangle ABC has  angles A=90 degrees, B=30. If side AC is 5 cm, how many cms is BC?')),
                ('thirdQuestion', models.FloatField(verbose_name='47/5=')),
                ('fourthQuestion', models.FloatField(verbose_name='13-2.3=')),
            ],
        ),
    ]
