# Generated by Django 2.0.1 on 2018-05-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_tests', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_1_math',
        ),
    ]
