# Generated by Django 2.0.1 on 2018-05-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_tests', '0003_test_1_math'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_1_math',
        ),
    ]
