# Generated by Django 2.0.1 on 2018-05-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_job_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_1',
        ),
    ]
