# Generated by Django 2.0.5 on 2018-05-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_job_1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_1',
            name='user',
            field=models.CharField(default='', max_length=80),
        ),
    ]
